{% set version = "0.7.0" %}

package:
  name: pystow
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pystow/pystow-{{ version }}.tar.gz
  sha256: 5f8935a76d5f03b0645bedbe5dfcb3b777a0e755fda3e3fd3e4be7a1d2d058d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}.*
    - pip
  imports:
    - pystow
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/pystow
  summary: Easily pick a place to store data for your python package.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://pystow.readthedocs.io/en/latest/
  dev_url: https://github.com/cthoyt/pystow

extra:
  recipe-maintainers:
    - cthoyt
