{% set version = "0.7.2" %}

package:
  name: pystow
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pystow/pystow-{{ version }}.tar.gz
  sha256: e50dd1ee034149f75236ea33a3fbf72245e41f60e8c763c10b1673dabe4bea1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}.*
    - pip
  imports:
    - pystow
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/pystow
  summary: Easily pick a place to store data for your python package.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://pystow.readthedocs.io/en/latest/
  dev_url: https://github.com/cthoyt/pystow

extra:
  recipe-maintainers:
    - cthoyt
