# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.10.2"

package:
  name: pystow
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pystow/pystow-${{ version }}.tar.gz
  sha256: e30ff664a9099ab9356b25e4fa3c69a1612a32c2c5b81e8a23b4c8efc2fb8a6d

build:
  number: 0
  python:
    entry_points:
      - pystow = pystow.cli:main
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --check-build-dependencies

requirements:
  host:
    - pip
    - python >=3.11
    - uv-build >=0.6.6,<1.0
  run:
    - backports.zstd
    - python >=${{ python_min }}
    - tqdm
    - typing_extensions

tests:
  - package_contents:
      strict: true
      site_packages:
        - pystow/**
        - pystow-${{ version }}.dist-info/**
  - python:
      imports: pystow
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pystow --help
      - pystow --version
      - pystow --version | ${{ "grep -iE " if unix else "findstr /r /c:" }}${{ version | replace(".", "\\.") }}

about:
  summary: Easily pick a place to store data for your Python code
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/pystow
  repository: https://github.com/cthoyt/pystow
  documentation: https://pystow.readthedocs.io

extra:
  recipe-maintainers:
    - cthoyt
    - bollwyvl
